# Generated by Django 4.2.4 on 2023-08-16 16:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "permission_id",
                    models.CharField(max_length=5, primary_key=True, serialize=False),
                ),
                ("permission_name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "role_id",
                    models.CharField(max_length=5, primary_key=True, serialize=False),
                ),
                ("role_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Role_Permission",
            fields=[
                (
                    "role_permission_id",
                    models.CharField(max_length=5, primary_key=True, serialize=False),
                ),
                (
                    "permission_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="supermarket_manager.permission",
                    ),
                ),
                (
                    "role_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="supermarket_manager.role",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "account_id",
                    models.CharField(max_length=5, primary_key=True, serialize=False),
                ),
                ("user_name", models.CharField(max_length=100)),
                ("login_name", models.CharField(max_length=100)),
                (
                    "password",
                    models.CharField(
                        max_length=30,
                        validators=[django.core.validators.MinLengthValidator(8)],
                    ),
                ),
                ("birth_day", models.DateField()),
                ("address", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=100)),
                (
                    "phone_number",
                    models.CharField(
                        max_length=10,
                        validators=[django.core.validators.RegexValidator("^0\\d{9}$")],
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("A", "Active"), ("D", "Disable")], max_length=1
                    ),
                ),
                (
                    "role_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="supermarket_manager.role",
                    ),
                ),
            ],
        ),
    ]
