# Generated by Django 4.2.4 on 2023-08-18 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supermarket_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permission",
            name="permission_id",
            field=models.AutoField(max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="role",
            name="role_id",
            field=models.AutoField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
