# Generated by Django 4.2.4 on 2023-08-18 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "supermarket_manager",
            "0002_alter_permission_permission_id_alter_role_role_id",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="permission",
            name="permission_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="role",
            name="role_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
