# Generated by Django 4.2.4 on 2023-08-18 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "supermarket_manager",
            "0003_alter_permission_permission_id_alter_role_role_id",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="role_permission",
            name="role_permission_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
