# Generated by Django 4.2.4 on 2023-08-29 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supermarket_manager", "0005_alter_role_role_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permission",
            name="permission_name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
