# Generated by Django 4.2.4 on 2023-08-29 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supermarket_manager", "0006_alter_permission_permission_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="role_permission",
            name="status",
            field=models.CharField(
                choices=[("A", "Active"), ("D", "Disable")], default="A", max_length=1
            ),
        ),
    ]
