# Generated by Django 4.2.4 on 2023-08-29 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supermarket_manager", "0007_role_permission_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="role_permission",
            name="status",
        ),
        migrations.AddField(
            model_name="permission",
            name="status",
            field=models.CharField(
                choices=[("A", "Active"), ("D", "Disable")], default="A", max_length=1
            ),
        ),
    ]
