# Generated by Django 4.2.4 on 2023-08-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supermarket_manager", "0008_remove_role_permission_status_permission_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="status",
            field=models.CharField(
                choices=[("A", "Active"), ("D", "Disable")], default="A", max_length=1
            ),
        ),
    ]
