# Generated by Django 4.2.4 on 2023-08-31 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supermarket_manager", "0009_alter_account_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="permission",
            field=models.ManyToManyField(
                through="supermarket_manager.Role_Permission",
                to="supermarket_manager.permission",
            ),
        ),
    ]
