# Generated by Django 4.2.4 on 2023-08-31 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supermarket_manager", "0010_role_permission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="email",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="login_name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
