# Generated by Django 4.2.4 on 2023-08-31 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supermarket_manager", "0011_alter_account_email_alter_account_login_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="account_id",
            field=models.AutoField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
