# Generated by Django 4.2.4 on 2023-08-31 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supermarket_manager", "0013_alter_account_account_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="login_name",
        ),
        migrations.AlterField(
            model_name="account",
            name="email",
            field=models.CharField(max_length=100),
        ),
    ]
