# Generated by Django 4.2.4 on 2023-09-05 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supermarket_manager", "0016_alter_account_account_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                default="M",
                max_length=1,
            ),
        ),
    ]
