# Generated by Django 4.2.4 on 2023-09-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "supermarket_manager",
            "0018_account_groups_account_is_active_account_is_staff_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="email",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
