# Generated by Django 4.2.4 on 2023-09-06 03:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supermarket_manager", "0019_alter_account_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="password",
            field=models.TextField(
                validators=[django.core.validators.MinLengthValidator(8)]
            ),
        ),
    ]
