# Generated by Django 4.2.4 on 2023-09-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supermarket_manager", "0020_alter_account_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="status",
            field=models.CharField(
                choices=[("Active", "Active"), ("Disabled", "Disabled")],
                default="Active",
                max_length=10,
            ),
        ),
    ]
