# Generated by Django 4.2.4 on 2023-09-18 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("supermarket_manager", "0021_alter_account_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="birth_day",
            new_name="birthday",
        ),
        migrations.RenameField(
            model_name="account",
            old_name="account_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="account",
            old_name="role_id",
            new_name="role",
        ),
        migrations.RenameField(
            model_name="permission",
            old_name="permission_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="permission",
            old_name="permission_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="role",
            old_name="role_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="role",
            old_name="role_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="role_permission",
            old_name="role_permission_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="role_permission",
            old_name="permission_id",
            new_name="permission",
        ),
        migrations.RenameField(
            model_name="role_permission",
            old_name="role_id",
            new_name="role",
        ),
    ]
